# Generated by Django 3.2.25 on 2024-07-16 01:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='athlete_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='coach_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skillja_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(900)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliverable', models.FileField(blank=True, null=True, upload_to='service_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='skillja_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='coach_profiles', to='skillja_app.Review'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='coach_profiles', to='skillja_app.Service'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='skillja_app.user'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='athlete_profiles', to='skillja_app.Review'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='skillja_app.user'),
        ),
    ]
