# Generated by Django 3.2.25 on 2024-09-24 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0002_auto_20240716_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='primary_sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='primary_sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('full-program', 'full-program'), ('online-program', 'online-program'), ('individual-session', 'individual-session')], default='individual-session', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='deliverable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialMedia', to='skillja_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='social_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to='skillja_app.socialmedia'),
        ),
    ]
