# Generated by Django 3.2.25 on 2024-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0003_auto_20240924_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='biography',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='primary_sport',
            field=models.CharField(blank=True, default='Not Specified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='biography',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='primary_sport',
            field=models.CharField(blank=True, default='Not Specified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, default='/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, default='/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, default='/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, default='/', max_length=255, null=True),
        ),
    ]
