# Generated by Django 3.2.25 on 2024-11-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0006_auto_20241108_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
