# Generated by Django 3.2.25 on 2024-12-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0008_auto_20241203_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='coach_profiles', to='skillja_app.Review'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='coach_profiles', to='skillja_app.Service'),
        ),
    ]
