# Generated by Django 3.2.25 on 2024-12-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0009_auto_20241203_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='coach_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='skillja_app.coachprofile'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='coach_services', to='skillja_app.Service'),
        ),
    ]
