# Generated by Django 3.2.25 on 2024-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0011_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='social_media',
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
