# Generated by Django 3.2.25 on 2024-12-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0012_auto_20241217_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_notifications', models.BooleanField(default=False)),
                ('email_appointment_notifications', models.BooleanField(default=False)),
                ('email_marketing_notifications', models.BooleanField(default=False)),
                ('account_deletion_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='skillja_app.user')),
            ],
        ),
    ]
