# Generated by Django 3.2.25 on 2025-01-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0015_auto_20250110_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='skillja_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='MonthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('is_current_month', models.BooleanField()),
                ('coach_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_schedules', to='skillja_app.coachavailability')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='skillja_app.monthschedule')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('month_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='skillja_app.monthschedule')),
            ],
            options={
                'unique_together': {('month_schedule', 'day_of_week')},
            },
        ),
    ]
