# Generated by Django 3.2.25 on 2025-01-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0016_blockedday_coachavailability_monthschedule_weeklyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthschedule',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
