# Generated by Django 3.2.25 on 2025-02-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0018_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='session_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
