# Generated by Django 3.2.25 on 2025-02-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0019_auto_20250206_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=110, null=True),
        ),
    ]
