# Generated by Django 3.2.25 on 2025-02-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0021_alter_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='session_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
