# Generated by Django 3.2.25 on 2025-02-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0022_event_session_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=40)),
                ('province_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='skillja_app_city_5079bc_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['province'], name='skillja_app_provinc_e0c55f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'province')},
        ),
    ]
