# Generated by Django 3.2.25 on 2025-02-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0025_auto_20250218_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='coach_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='skillja_app.coachprofile'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='coach_reviews', to='skillja_app.Review'),
        ),
    ]
