# Generated by Django 3.2.25 on 2025-02-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillja_app', '0026_auto_20250219_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
